name: Auto NSFW Push

on:
  schedule:
    - cron: "0 */2 * * *"  # 每2小时执行一次
  workflow_dispatch:

jobs:
  push-nsfw:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Debug environment variables
      run: |
        echo "BOT_TOKEN length: ${#BOT_TOKEN}"
        echo "CHANNEL_USERNAME: $CHANNEL_USERNAME"
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHANNEL_USERNAME: ${{ secrets.CHANNEL_USERNAME }}

    - name: Run crawler and push images
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHANNEL_USERNAME: ${{ secrets.CHANNEL_USERNAME }}
      run: |
        python crawler.py
        python main.py
